/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package companydbmanagerant.view;

import companydbmanagerant.view.Main.MainForm;
import companydbmanagerant.view.Login.LoginForm;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import companydbmanagerant.view.Main.QueryBuilderForm.Querybuilderform;
import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import raven.toast.Notifications;

/**
 *
 * @author PHC
 */
public class DataView extends javax.swing.JFrame {

    private final MainForm mainForm;
    private final LoginForm loginForm;
    private Querybuilderform querybuilderform;

    /**
     * Creates new form MainFrame
     */
    public DataView() {
        initComponents();
        querybuilderform = null;
        mainForm = new MainForm();
        loginForm = new LoginForm();

        init();
    }

    private void init() {
        setSize(new Dimension(1050, 600));
        setContentPane(loginForm);
        Notifications.getInstance().setJFrame(this);
        FlatLaf.updateUI();
    }

    public Querybuilderform getQuerybuilderform() {
        return querybuilderform;
    }

    public void setQuerybuilderform(Querybuilderform querybuilderform) {
        this.querybuilderform = querybuilderform;
    }

    public MainForm getMainForm() {
        return mainForm;
    }

    public LoginForm getLoginForm() {
        return loginForm;
    }

    public void showMainForm() {
        setContentPane(mainForm);
        FlatLaf.updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CompanyDBManager");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void showGUI() {
        // GUI 요소가 준비된 후에 텍스트 필드에 포커스를 설정합니다.
        pack();
        setVisible(true);

        // GUI 이벤트 처리 스레드에서 실행될 작업을 예약
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JTextField textField = loginForm.getTxtPass(); // LoginForm 내부의 텍스트 필드 접근 메서드가 필요합니다.
                textField.requestFocusInWindow();
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //FlatLightLaf.setup();

//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("FlatLaf Dark".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        DataView dataView = new DataView();
        dataView.showGUI();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
